name: Re-run 
on:
  workflow_run:
    workflows: ["Add Rules to Cloudflare Gateway"]
    types:
      - completed
jobs:
  retry1:
    name: Cloudflare Gateway
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    runs-on: ubuntu-latest
    
    steps:
      - name: Delay for 300 seconds
        run: sleep 300
        
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install aiohttp

      - name: Cloudflare Gateway Zero Trust
        run: python -m src
        env:
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CF_IDENTIFIER: ${{ secrets.CF_IDENTIFIER }}
          PYTHONDONTWRITEBYTECODE: 1
